# Generated by Django 2.2.16 on 2022-10-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20221007_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title_id',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='title_id',
            new_name='title',
        ),
    ]
