# Generated by Django 2.2.16 on 2022-10-07 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20221007_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='title',
        ),
    ]
