# Generated by Django 2.2.19 on 2022-10-13 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20221013_2210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': ('Категория',), 'verbose_name_plural': ('Категории',)},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': ('Жанр',), 'verbose_name_plural': ('Жанры',)},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': ('Произведение',), 'verbose_name_plural': ('Произведения',)},
        ),
    ]
