# Generated by Django 2.2.16 on 2022-10-07 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20221007_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='title',
        ),
    ]
