# Generated by Django 2.2.19 on 2022-10-13 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20221013_2253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': ('category1',), 'verbose_name_plural': ('categories1',)},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': ('genre1',), 'verbose_name_plural': ('genres1',)},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': ('title1',), 'verbose_name_plural': ('titles1',)},
        ),
    ]
