# Generated by Django 2.2.19 on 2022-10-13 23:11

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20221013_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(datetime.datetime.utcnow), django.core.validators.MinValueValidator(-4000)]),
        ),
    ]
