# Generated by Django 2.2.19 on 2022-10-14 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_auto_20221014_0020'),
        ('reviews', '0008_auto_20221013_2241'),
    ]

    operations = [
    ]
