# Generated by Django 2.2.19 on 2022-10-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0015_merge_20221014_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.TextField(db_index=True, max_length=256, verbose_name='Название произедения'),
        ),
    ]
